"""Add module_id to forms blueprints and cases

Revision ID: 095205000a8b
Revises: bd3f3da4556e
Create Date: 2026-03-24 17:51:58.153540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '095205000a8b'
down_revision: Union[str, Sequence[str], None] = 'bd3f3da4556e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
