"""add_module_categories

Revision ID: 0c6c4bdb740c
Revises: 5b9747bf93dc
Create Date: 2026-04-03 00:03:31.689605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6c4bdb740c'
down_revision: Union[str, Sequence[str], None] = '5b9747bf93dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'modules', 'module_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.drop_column('modules', 'category_id')
    # ### end Alembic commands ###
