"""Agrega favorite_offers a User

Revision ID: 11378e11153e
Revises: 97407d64c0d3
Create Date: 2026-05-04 12:07:35.016588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11378e11153e'
down_revision: Union[str, Sequence[str], None] = '97407d64c0d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_offers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_offers')
    # ### end Alembic commands ###
