"""add_created_at_to_templates

Revision ID: 1478a5a6163f
Revises: 18ea9b980caf
Create Date: 2026-04-12 15:46:05.316914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1478a5a6163f'
down_revision: Union[str, Sequence[str], None] = '18ea9b980caf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_templates', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('document_templates', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_templates', 'updated_at')
    op.drop_column('document_templates', 'created_at')
    # ### end Alembic commands ###
