"""add_company_id_to_modules

Revision ID: 198fe5a22f19
Revises: ad855244c0bc
Create Date: 2026-03-30 19:37:33.523391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '198fe5a22f19'
down_revision: Union[str, Sequence[str], None] = 'ad855244c0bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_modules_company_id'), 'modules', ['company_id'], unique=False)
    op.create_foreign_key(None, 'modules', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.drop_index(op.f('ix_modules_company_id'), table_name='modules')
    op.drop_column('modules', 'company_id')
    # ### end Alembic commands ###
