"""fase_2_sla_motor

Revision ID: 26ade799fd9b
Revises: bf447096559b
Create Date: 2026-04-06 17:05:03.252235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ade799fd9b'
down_revision: Union[str, Sequence[str], None] = 'bf447096559b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('entered_status_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('statuses', sa.Column('sla_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statuses', 'sla_hours')
    op.drop_column('cases', 'entered_status_at')
    # ### end Alembic commands ###
