"""add_mobile_config_to_modules

Revision ID: 2c677354d39d
Revises: 3e758bd87edf
Create Date: 2026-04-27 17:57:01.413011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c677354d39d'
down_revision: Union[str, Sequence[str], None] = '3e758bd87edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('mobile_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'mobile_config')
    # ### end Alembic commands ###
