"""fase_soporte_tablas

Revision ID: 3529c3d28dda
Revises: 5060d2cddc61
Create Date: 2026-04-08 16:21:56.962576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3529c3d28dda'
down_revision: Union[str, Sequence[str], None] = '5060d2cddc61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('client_user_id', sa.Integer(), nullable=True),
    sa.Column('agent_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('csat_score', sa.Integer(), nullable=True),
    sa.Column('csat_comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_sessions_agent_user_id'), 'support_sessions', ['agent_user_id'], unique=False)
    op.create_index(op.f('ix_support_sessions_client_user_id'), 'support_sessions', ['client_user_id'], unique=False)
    op.create_index(op.f('ix_support_sessions_company_id'), 'support_sessions', ['company_id'], unique=False)
    op.create_index(op.f('ix_support_sessions_id'), 'support_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_support_sessions_started_at'), 'support_sessions', ['started_at'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_internal_note', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['support_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.add_column('companies', sa.Column('is_system_company', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'is_system_company')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_support_sessions_started_at'), table_name='support_sessions')
    op.drop_index(op.f('ix_support_sessions_id'), table_name='support_sessions')
    op.drop_index(op.f('ix_support_sessions_company_id'), table_name='support_sessions')
    op.drop_index(op.f('ix_support_sessions_client_user_id'), table_name='support_sessions')
    op.drop_index(op.f('ix_support_sessions_agent_user_id'), table_name='support_sessions')
    op.drop_table('support_sessions')
    # ### end Alembic commands ###
