"""add_bpmn_shape_to_status

Revision ID: 364079ffee55
Revises: ba0d6d6a76b7
Create Date: 2026-04-08 00:44:58.537327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '364079ffee55'
down_revision: Union[str, Sequence[str], None] = 'ba0d6d6a76b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('bpmn_shape', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statuses', 'bpmn_shape')
    # ### end Alembic commands ###
