"""add_options_to_fields

Revision ID: 3cf79174a56b
Revises: 4daa74f78309
Create Date: 2026-03-23 16:37:26.493858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf79174a56b'
down_revision: Union[str, Sequence[str], None] = '4daa74f78309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_fields', sa.Column('options', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_fields', 'options')
    # ### end Alembic commands ###
