"""Agregando secciones y subformularios

Revision ID: 3e1079171c36
Revises: e7d8a7c6419d
Create Date: 2026-03-26 17:45:51.013651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1079171c36'
down_revision: Union[str, Sequence[str], None] = 'e7d8a7c6419d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_fields', sa.Column('section_id', sa.Integer(), nullable=True))
    op.add_column('form_fields', sa.Column('subform_config', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('form_fields_form_id_fkey'), 'form_fields', type_='foreignkey')
    op.create_foreign_key(None, 'form_fields', 'forms', ['form_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'form_fields', 'form_sections', ['section_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'form_fields', type_='foreignkey')
    op.drop_constraint(None, 'form_fields', type_='foreignkey')
    op.create_foreign_key(op.f('form_fields_form_id_fkey'), 'form_fields', 'forms', ['form_id'], ['id'])
    op.drop_column('form_fields', 'subform_config')
    op.drop_column('form_fields', 'section_id')
    # ### end Alembic commands ###
