"""add_external_users_and_portals

Revision ID: 3e758bd87edf
Revises: 91c6eacca998
Create Date: 2026-04-27 13:09:34.194130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e758bd87edf'
down_revision: Union[str, Sequence[str], None] = '91c6eacca998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('is_external', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('portal_access', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('is_external', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('contact_record_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contact_record_id')
    op.drop_column('users', 'is_external')
    op.drop_column('profiles', 'portal_access')
    op.drop_column('profiles', 'is_external')
    # ### end Alembic commands ###
