"""add_blueprints

Revision ID: 4daa74f78309
Revises: cdcbe70ccaf4
Create Date: 2026-03-23 15:41:33.321125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4daa74f78309'
down_revision: Union[str, Sequence[str], None] = 'cdcbe70ccaf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('blueprint_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'statuses', 'blueprints', ['blueprint_id'], ['id'])
    op.add_column('transitions', sa.Column('blueprint_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transitions', 'blueprints', ['blueprint_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transitions', type_='foreignkey')
    op.drop_column('transitions', 'blueprint_id')
    op.drop_constraint(None, 'statuses', type_='foreignkey')
    op.drop_column('statuses', 'blueprint_id')
    # ### end Alembic commands ###
