"""Add ui_rules

Revision ID: 50157ac235ad
Revises: 3254922754fa
Create Date: 2026-03-24 23:04:18.561275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50157ac235ad'
down_revision: Union[str, Sequence[str], None] = '3254922754fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('ui_rules', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'ui_rules')
    # ### end Alembic commands ###
