"""add_position_to_status

Revision ID: 5060d2cddc61
Revises: 364079ffee55
Create Date: 2026-04-08 01:17:01.045796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5060d2cddc61'
down_revision: Union[str, Sequence[str], None] = '364079ffee55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('position_x', sa.Integer(), nullable=True))
    op.add_column('statuses', sa.Column('position_y', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statuses', 'position_y')
    op.drop_column('statuses', 'position_x')
    # ### end Alembic commands ###
