"""Add mobile_app_config to Company

Revision ID: 52f7a5d0d1a2
Revises: da48c48f2576
Create Date: 2026-05-07 18:20:40.108528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f7a5d0d1a2'
down_revision: Union[str, Sequence[str], None] = 'da48c48f2576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('mobile_app_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'mobile_app_config')
    # ### end Alembic commands ###
