"""Add RoundRobinTracker and TransitionValidation tables

Revision ID: 5b9747bf93dc
Revises: 71982cda18bd
Create Date: 2026-03-31 23:47:16.465166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b9747bf93dc'
down_revision: Union[str, Sequence[str], None] = '71982cda18bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
