"""add_show_in_create_to_fields

Revision ID: 61da04878b41
Revises: 65550c28e00a
Create Date: 2026-03-24 00:14:05.609628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61da04878b41'
down_revision: Union[str, Sequence[str], None] = '65550c28e00a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_fields', sa.Column('show_in_create', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_fields', 'show_in_create')
    # ### end Alembic commands ###
