"""add_concurrent_sessions_and_pwd_complexity

Revision ID: 6a9c8c8aecd5
Revises: bef645e246a0
Create Date: 2026-04-03 15:08:44.330862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a9c8c8aecd5'
down_revision: Union[str, Sequence[str], None] = 'bef645e246a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token_jti', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_sessions_company_id'), 'active_sessions', ['company_id'], unique=False)
    op.create_index(op.f('ix_active_sessions_id'), 'active_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_active_sessions_token_jti'), 'active_sessions', ['token_jti'], unique=True)
    op.create_index(op.f('ix_active_sessions_user_id'), 'active_sessions', ['user_id'], unique=False)
    op.add_column('security_policies', sa.Column('max_concurrent_sessions', sa.Integer(), nullable=True))
    op.add_column('security_policies', sa.Column('password_complexity_active', sa.Boolean(), nullable=True))
    op.add_column('security_policies', sa.Column('pwd_min_length', sa.Integer(), nullable=True))
    op.add_column('security_policies', sa.Column('pwd_max_length', sa.Integer(), nullable=True))
    op.add_column('security_policies', sa.Column('pwd_require_uppercase', sa.Boolean(), nullable=True))
    op.add_column('security_policies', sa.Column('pwd_require_lowercase', sa.Boolean(), nullable=True))
    op.add_column('security_policies', sa.Column('pwd_require_numbers', sa.Boolean(), nullable=True))
    op.add_column('security_policies', sa.Column('pwd_require_special', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security_policies', 'pwd_require_special')
    op.drop_column('security_policies', 'pwd_require_numbers')
    op.drop_column('security_policies', 'pwd_require_lowercase')
    op.drop_column('security_policies', 'pwd_require_uppercase')
    op.drop_column('security_policies', 'pwd_max_length')
    op.drop_column('security_policies', 'pwd_min_length')
    op.drop_column('security_policies', 'password_complexity_active')
    op.drop_column('security_policies', 'max_concurrent_sessions')
    op.drop_index(op.f('ix_active_sessions_user_id'), table_name='active_sessions')
    op.drop_index(op.f('ix_active_sessions_token_jti'), table_name='active_sessions')
    op.drop_index(op.f('ix_active_sessions_id'), table_name='active_sessions')
    op.drop_index(op.f('ix_active_sessions_company_id'), table_name='active_sessions')
    op.drop_table('active_sessions')
    # ### end Alembic commands ###
