"""Add deleted_by column to Case model

Revision ID: 71982cda18bd
Revises: bf118b13f502
Create Date: 2026-03-31 15:59:44.850743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71982cda18bd'
down_revision: Union[str, Sequence[str], None] = 'bf118b13f502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cases', 'users', ['deleted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_column('cases', 'deleted_by')
    # ### end Alembic commands ###
