"""add_forms_and_api_names

Revision ID: 7edec3bca735
Revises: 61da04878b41
Create Date: 2026-03-24 00:54:58.854487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7edec3bca735'
down_revision: Union[str, Sequence[str], None] = '61da04878b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('form_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cases', 'forms', ['form_id'], ['id'])
    op.add_column('form_fields', sa.Column('form_id', sa.Integer(), nullable=True))
    op.add_column('form_fields', sa.Column('api_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_form_fields_api_name'), 'form_fields', ['api_name'], unique=False)
    op.create_foreign_key(None, 'form_fields', 'forms', ['form_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'form_fields', type_='foreignkey')
    op.drop_index(op.f('ix_form_fields_api_name'), table_name='form_fields')
    op.drop_column('form_fields', 'api_name')
    op.drop_column('form_fields', 'form_id')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_column('cases', 'form_id')
    # ### end Alembic commands ###
