"""add_custom_smtp_to_company

Revision ID: 8aa00b9df518
Revises: ddf5180d5d97
Create Date: 2026-04-04 11:53:43.509435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa00b9df518'
down_revision: Union[str, Sequence[str], None] = 'ddf5180d5d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('use_custom_smtp', sa.Boolean(), nullable=True))
    op.add_column('companies', sa.Column('smtp_host', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('smtp_user', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('smtp_password', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('smtp_from_email', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('smtp_from_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'smtp_from_name')
    op.drop_column('companies', 'smtp_from_email')
    op.drop_column('companies', 'smtp_password')
    op.drop_column('companies', 'smtp_user')
    op.drop_column('companies', 'smtp_port')
    op.drop_column('companies', 'smtp_host')
    op.drop_column('companies', 'use_custom_smtp')
    # ### end Alembic commands ###
