"""add_signaturit_integration_models

Revision ID: 91c6eacca998
Revises: 682fba87791b
Create Date: 2026-04-25 15:06:44.347457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c6eacca998'
down_revision: Union[str, Sequence[str], None] = '682fba87791b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('encrypted_token', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_integrations_company_id'), 'module_integrations', ['company_id'], unique=False)
    op.create_index(op.f('ix_module_integrations_id'), 'module_integrations', ['id'], unique=False)
    op.create_index(op.f('ix_module_integrations_module_id'), 'module_integrations', ['module_id'], unique=False)
    op.create_index(op.f('ix_module_integrations_provider_name'), 'module_integrations', ['provider_name'], unique=False)
    op.create_table('signature_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('signaturit_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('signers_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signature_requests_case_id'), 'signature_requests', ['case_id'], unique=False)
    op.create_index(op.f('ix_signature_requests_company_id'), 'signature_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_signature_requests_id'), 'signature_requests', ['id'], unique=False)
    op.create_index(op.f('ix_signature_requests_signaturit_id'), 'signature_requests', ['signaturit_id'], unique=True)
    op.create_index(op.f('ix_signature_requests_status'), 'signature_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signature_requests_status'), table_name='signature_requests')
    op.drop_index(op.f('ix_signature_requests_signaturit_id'), table_name='signature_requests')
    op.drop_index(op.f('ix_signature_requests_id'), table_name='signature_requests')
    op.drop_index(op.f('ix_signature_requests_company_id'), table_name='signature_requests')
    op.drop_index(op.f('ix_signature_requests_case_id'), table_name='signature_requests')
    op.drop_table('signature_requests')
    op.drop_index(op.f('ix_module_integrations_provider_name'), table_name='module_integrations')
    op.drop_index(op.f('ix_module_integrations_module_id'), table_name='module_integrations')
    op.drop_index(op.f('ix_module_integrations_id'), table_name='module_integrations')
    op.drop_index(op.f('ix_module_integrations_company_id'), table_name='module_integrations')
    op.drop_table('module_integrations')
    # ### end Alembic commands ###
