"""Add parent_id to roles

Revision ID: 9a40ed807184
Revises: fde44900d05a
Create Date: 2026-03-27 14:43:06.776449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a40ed807184'
down_revision: Union[str, Sequence[str], None] = 'fde44900d05a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'roles', 'roles', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'parent_id')
    # ### end Alembic commands ###
