"""Add action_config to TransitionAction

Revision ID: 9fa11936acee
Revises: ac53e00fb7dd
Create Date: 2026-03-27 10:33:58.093633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa11936acee'
down_revision: Union[str, Sequence[str], None] = 'ac53e00fb7dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transition_actions', sa.Column('action_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transition_actions', 'action_config')
    # ### end Alembic commands ###
