"""Add ImportBatch and import tracking to Cases

Revision ID: ac53e00fb7dd
Revises: 3e1079171c36
Create Date: 2026-03-27 00:09:06.853994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac53e00fb7dd'
down_revision: Union[str, Sequence[str], None] = '3e1079171c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('import_batch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cases', 'import_batches', ['import_batch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_column('cases', 'import_batch_id')
    # ### end Alembic commands ###
