"""add_is_active_to_fields

Revision ID: ae9a34403c8e
Revises: 3cf79174a56b
Create Date: 2026-03-23 16:46:16.418316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae9a34403c8e'
down_revision: Union[str, Sequence[str], None] = '3cf79174a56b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_fields', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_fields', 'is_active')
    # ### end Alembic commands ###
