"""add_ai_settings_to_company

Revision ID: ba0d6d6a76b7
Revises: d23f6fa027cd
Create Date: 2026-04-07 10:12:48.283930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba0d6d6a76b7'
down_revision: Union[str, Sequence[str], None] = 'd23f6fa027cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('ai_active_provider', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('ai_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'ai_api_key')
    op.drop_column('companies', 'ai_active_provider')
    # ### end Alembic commands ###
