"""add_mfa_and_granular_policies

Revision ID: ba2b1906780f
Revises: 6a9c8c8aecd5
Create Date: 2026-04-03 15:58:03.078497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2b1906780f'
down_revision: Union[str, Sequence[str], None] = '6a9c8c8aecd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_policies', sa.Column('name', sa.String(), nullable=True))
    op.add_column('security_policies', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.add_column('security_policies', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('security_policies', sa.Column('mfa_active', sa.Boolean(), nullable=True))
    op.add_column('security_policies', sa.Column('mfa_required', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_security_policies_company_id'), table_name='security_policies')
    op.create_index(op.f('ix_security_policies_company_id'), 'security_policies', ['company_id'], unique=False)
    op.create_index(op.f('ix_security_policies_profile_id'), 'security_policies', ['profile_id'], unique=False)
    op.create_index(op.f('ix_security_policies_role_id'), 'security_policies', ['role_id'], unique=False)
    op.create_foreign_key(None, 'security_policies', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'security_policies', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('mfa_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_mfa_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_mfa_enabled')
    op.drop_column('users', 'mfa_secret')
    op.drop_constraint(None, 'security_policies', type_='foreignkey')
    op.drop_constraint(None, 'security_policies', type_='foreignkey')
    op.drop_index(op.f('ix_security_policies_role_id'), table_name='security_policies')
    op.drop_index(op.f('ix_security_policies_profile_id'), table_name='security_policies')
    op.drop_index(op.f('ix_security_policies_company_id'), table_name='security_policies')
    op.create_index(op.f('ix_security_policies_company_id'), 'security_policies', ['company_id'], unique=True)
    op.drop_column('security_policies', 'mfa_required')
    op.drop_column('security_policies', 'mfa_active')
    op.drop_column('security_policies', 'role_id')
    op.drop_column('security_policies', 'profile_id')
    op.drop_column('security_policies', 'name')
    # ### end Alembic commands ###
