"""Add modules table and module_id to forms/blueprints

Revision ID: bd3f3da4556e
Revises: ede7d55dc791
Create Date: 2026-03-24 16:26:18.364746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3f3da4556e'
down_revision: Union[str, Sequence[str], None] = 'ede7d55dc791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blueprints', sa.Column('module_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blueprints', 'modules', ['module_id'], ['id'])
    op.add_column('forms', sa.Column('module_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'forms', 'modules', ['module_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forms', type_='foreignkey')
    op.drop_column('forms', 'module_id')
    op.drop_constraint(None, 'blueprints', type_='foreignkey')
    op.drop_column('blueprints', 'module_id')
    # ### end Alembic commands ###
