"""add module_id to cases

Revision ID: bd41c113bea1
Revises: 095205000a8b
Create Date: 2026-03-24 17:57:34.286022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd41c113bea1'
down_revision: Union[str, Sequence[str], None] = '095205000a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('module_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cases', 'modules', ['module_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_column('cases', 'module_id')
    # ### end Alembic commands ###
