"""add_security_policies_and_trackers

Revision ID: bef645e246a0
Revises: 0b9f2cadf6f9
Create Date: 2026-04-03 12:28:56.915652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef645e246a0'
down_revision: Union[str, Sequence[str], None] = '0b9f2cadf6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('max_login_attempts', sa.Integer(), nullable=True),
    sa.Column('temp_lockout_minutes', sa.Integer(), nullable=True),
    sa.Column('max_temp_lockouts', sa.Integer(), nullable=True),
    sa.Column('password_expiration_active', sa.Boolean(), nullable=True),
    sa.Column('password_expiration_days', sa.Integer(), nullable=True),
    sa.Column('password_history_active', sa.Boolean(), nullable=True),
    sa.Column('password_history_count', sa.Integer(), nullable=True),
    sa.Column('inactivity_timeout_minutes', sa.Integer(), nullable=True),
    sa.Column('ip_whitelist_active', sa.Boolean(), nullable=True),
    sa.Column('allowed_ips', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_policies_company_id'), 'security_policies', ['company_id'], unique=True)
    op.create_index(op.f('ix_security_policies_id'), 'security_policies', ['id'], unique=False)
    op.create_table('password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_history_company_id'), 'password_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_password_history_id'), 'password_history', ['id'], unique=False)
    op.create_index(op.f('ix_password_history_user_id'), 'password_history', ['user_id'], unique=False)
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('temp_lockouts_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'temp_lockouts_count')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_index(op.f('ix_password_history_user_id'), table_name='password_history')
    op.drop_index(op.f('ix_password_history_id'), table_name='password_history')
    op.drop_index(op.f('ix_password_history_company_id'), table_name='password_history')
    op.drop_table('password_history')
    op.drop_index(op.f('ix_security_policies_id'), table_name='security_policies')
    op.drop_index(op.f('ix_security_policies_company_id'), table_name='security_policies')
    op.drop_table('security_policies')
    # ### end Alembic commands ###
