"""add_composite_unique_module

Revision ID: bf118b13f502
Revises: 198fe5a22f19
Create Date: 2026-03-30 23:14:12.013919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf118b13f502'
down_revision: Union[str, Sequence[str], None] = '198fe5a22f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modules_name'), table_name='modules')
    op.create_index(op.f('ix_modules_name'), 'modules', ['name'], unique=False)
    op.create_unique_constraint('uix_company_module_name', 'modules', ['company_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_company_module_name', 'modules', type_='unique')
    op.drop_index(op.f('ix_modules_name'), table_name='modules')
    op.create_index(op.f('ix_modules_name'), 'modules', ['name'], unique=True)
    # ### end Alembic commands ###
