"""Add versioning to Blueprints and CaseComments table

Revision ID: bf447096559b
Revises: bcc1a1360b5b
Create Date: 2026-04-06 11:40:34.593368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf447096559b'
down_revision: Union[str, Sequence[str], None] = 'bcc1a1360b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_system_message', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_comments_case_id'), 'case_comments', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_comments_company_id'), 'case_comments', ['company_id'], unique=False)
    op.create_index(op.f('ix_case_comments_created_at'), 'case_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_case_comments_id'), 'case_comments', ['id'], unique=False)
    op.add_column('blueprints', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('blueprints', sa.Column('is_draft', sa.Boolean(), nullable=True))
    op.add_column('blueprints', sa.Column('parent_blueprint_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blueprints', 'blueprints', ['parent_blueprint_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blueprints', type_='foreignkey')
    op.drop_column('blueprints', 'parent_blueprint_id')
    op.drop_column('blueprints', 'is_draft')
    op.drop_column('blueprints', 'version')
    op.drop_index(op.f('ix_case_comments_id'), table_name='case_comments')
    op.drop_index(op.f('ix_case_comments_created_at'), table_name='case_comments')
    op.drop_index(op.f('ix_case_comments_company_id'), table_name='case_comments')
    op.drop_index(op.f('ix_case_comments_case_id'), table_name='case_comments')
    op.drop_table('case_comments')
    # ### end Alembic commands ###
