"""Add Dashboards and Reports tables

Revision ID: c0e2e17adf38
Revises: 114b0dfc8089
Create Date: 2026-03-28 01:15:41.983312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0e2e17adf38'
down_revision: Union[str, Sequence[str], None] = '114b0dfc8089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
