"""Add assigned_to and user names

Revision ID: d72ed26729b5
Revises: debd940765ff
Create Date: 2026-03-25 14:06:12.073345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd72ed26729b5'
down_revision: Union[str, Sequence[str], None] = 'debd940765ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cases', 'users', ['assigned_to'], ['id'])
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_column('cases', 'assigned_to')
    # ### end Alembic commands ###
