"""Add external chat

Revision ID: da48c48f2576
Revises: 11378e11153e
Create Date: 2026-05-05 02:06:56.622444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da48c48f2576'
down_revision: Union[str, Sequence[str], None] = '11378e11153e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_external_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_from_client', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_external_messages_case_id'), 'case_external_messages', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_external_messages_company_id'), 'case_external_messages', ['company_id'], unique=False)
    op.create_index(op.f('ix_case_external_messages_created_at'), 'case_external_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_case_external_messages_id'), 'case_external_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_external_messages_id'), table_name='case_external_messages')
    op.drop_index(op.f('ix_case_external_messages_created_at'), table_name='case_external_messages')
    op.drop_index(op.f('ix_case_external_messages_company_id'), table_name='case_external_messages')
    op.drop_index(op.f('ix_case_external_messages_case_id'), table_name='case_external_messages')
    op.drop_table('case_external_messages')
    # ### end Alembic commands ###
