"""Add function code to transition actions

Revision ID: e09fc9916397
Revises: 87bbd8e5b498
Create Date: 2026-03-25 10:04:59.687171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e09fc9916397'
down_revision: Union[str, Sequence[str], None] = '87bbd8e5b498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transition_actions', sa.Column('function_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transition_actions', 'function_code')
    # ### end Alembic commands ###
