"""Add is_primary

Revision ID: e7d8a7c6419d
Revises: af5206f422fe
Create Date: 2026-03-26 15:12:55.066535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d8a7c6419d'
down_revision: Union[str, Sequence[str], None] = 'af5206f422fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_fields', sa.Column('is_primary', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_fields', 'is_primary')
    # ### end Alembic commands ###
