"""add_deleted_at_to_cases

Revision ID: ede7d55dc791
Revises: 7edec3bca735
Create Date: 2026-03-24 12:37:23.904855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede7d55dc791'
down_revision: Union[str, Sequence[str], None] = '7edec3bca735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'deleted_at')
    # ### end Alembic commands ###
