"""Add action_config to AutomationRule

Revision ID: fde44900d05a
Revises: 9fa11936acee
Create Date: 2026-03-27 13:17:21.669875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde44900d05a'
down_revision: Union[str, Sequence[str], None] = '9fa11936acee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automation_rules', sa.Column('action_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('automation_rules', 'action_config')
    # ### end Alembic commands ###
